### ISSUE TITLE
How to run the code on any videos?

### ISSUE THREAD

**Issue by KasraMokhtari2112** [thatbrguy/Pedestrian-Detector#4]
Hi, This is awesome!
Can you please help to figure it out how I have to use this code to detect pedestrians on any videos? I am very new to Python!

Thank you so much!
Kasra,

**Comment by thatbrguy** [comment]
Hello, right now you have to feed data as images to `object_dection/inference.py`. You can check out OpenCV's `VideoCapture` function to modify the code in `inference.py` for it to work directly on videos.
