### ISSUE TITLE
Is there a limit to the number of bounding boxes ?

### ISSUE THREAD

**Issue by MounirB** [thatbrguy/Pedestrian-Detector#7]
Hello,

When I extracted the bounding boxes of a crowded scene, I found that the array associated to the bounding boxes has got a limit of 100 rows. Does it mean that if an image has more than 100 pedestrians the detector won't put them all in bounding boxes ?

How about training ? Can we train a model with a dataset of images that contains more than 100 pedestrians ?

Thank you in advance for your clarifications !

**Comment by thatbrguy** [comment]
You can adjust these values by setting the appropriate attribute in your `pipeline.config` file. Should be pretty easy to spot!

**Comment by MounirB** [comment]
These parameters :
>  max_detections_per_class: 100
> max_total_detections: 100

Thanks for your help @thatbrguy !
